name: discrepancy_test

on: [push, pull_request]

jobs:
  grade:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout student code
      uses: actions/checkout@v2

    - name: Checkout grading scripts
      uses: actions/checkout@v2
      with:
        repository: ZhiLiu724/orie5355_upload_test
        path: orie5355_upload_test

    - name: Install Dependencies
      run: 
        echo '------INSTALLING DEPENDENCIES------'
        sudo -H pip3 install -r orie5355_upload_test/requirements.txt